language: objective-c
 
env:
  matrix:
    - TEST_TYPE=ios-unit-test
    - TEST_TYPE=ios-integration-test
    - TEST_TYPE=android-unit-test
    - TEST_TYPE=android-integration-test
  global:
    - DIRECTORY_ANDROID=android
    - DIRECTORY_IOS=ios
    - PROJECT_MOBILE=MitMartRN
 
cache:
  directories:
  - node_modules
 
before_install:
  - brew update
 
install:
  - brew reinstall gradle flow watchman xctool
 
branches:
  only:
    - travis
 
script:
- |
  if [ "$TEST_TYPE" = android-unit-test ]
  then
 
    npm install
    flow check
    npm test
 
  elif [ "$TEST_TYPE" = android-integration-test ]
  then
  
    npm install
    npm start
    cd $DIRECTORY_ANDROID
    gradle build connectedCheck
 
  elif [ "$TEST_TYPE" = ios-unit-test ]
  then
  
    npm install
    flow check
    npm test
 
  elif [ "$TEST_TYPE" = ios-integration-test ]
  then

    npm install
    npm start
    
    cd $DIRECTORY_IOS
    
    xctool \
      -project $PROJECT_MOBILE.xcodeproj \
      -scheme $PROJECT_MOBILE -sdk iphonesimulator8.1
      test
 
    pkill -9 -F packager.pid
    cat packager.log
    rm packager.log packager.pid
 
  else
    echo "Unknown test type: $TEST_TYPE"
    exit 1
  fi